### ISSUE TITLE
Encountered KeyError when attempting to supply secrets via x-secrets: in docker-compose.yml file 

### ISSUE THREAD

**Issue by pramodvkrishna** [compose-x/ecs_composex#414]
**Describe the bug**
An error(WARNING) "KeyError: ('For Secrets JSON Key support, you must specify', ['SecretKey'], 'Got', dict_keys(['Key', 'Name']))" encountered whilst running ecs-compose-x command

**To Reproduce**
1. How you installed ECS ComposeX'...'
    We use AWS Codebuild to generate the CFN templates using ecs-compose-x. The Codebuild image is 
    aws/codebuild/standard:4.0. Command used in buildspec.yml file is 
    pip install git+https://github.com/lambda-my-aws/ecs_composex@main
2. How you are executing it ? : As a CLI tool, as a library, in lambda?
    Executing the cli command
    ecs-compose-x create -n ${DEPLOYMENT_NAME:-dis-by-http-client} --format yaml -f docker-compose.yml -f envs/dev.yml \
        -b ${CFN_TPL_BUCKET} -d outputs/dev/
    
3. Link / share your Docker compose file

docker-compose.yml

---
# Docker-compose file for by-http-client service

services:
  xyz-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${JAR_FILE:-xyz_client.0.0.1-SNAPSHOT.jar}
    image: ${REGISTRY_URI}xyz-client:${IMAGE_TAG:-latest}
    x-configs:
      iam:
        policies:
          - name: CWMetricsPublishingAccess
            document:
              Version: "2012-10-17"
              Statement:
                - Sid: "AllowCWAccess"
                  Action:
                    - "cloudwatch:PutMetric*"
                  Effect: Allow
                  Resource:
                    - "*"
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: 0.5
          memory: 1GB
    environment:
      JAVA_OPTS: -Xms512m -Xmx1G

 dev.yml file contents  
---
# Docker compose override file for AWS dev environment

version: "3.8"
x-cluster:
  Use: ${ENV_NAME:-dev}

x-vpc:
  Lookup:
    VpcId:
      Tags:
        - Name: vpc--xyz
    AppSubnets:
      Tags:
        - vpc::usage: application
        - vpc::internal: "true"
        - vpc::primary: "false"
    PublicSubnets:
      Tags:
        - vpc::usage: public
    StorageSubnets:
      Tags:
        - vpc::usage: storage
    RoleArn: ${NONPROD_RO_ROLE_ARN}

services:
  xyz-client:
    x-iam:
      PermissionsBoundary: ccoe/xyz-developer
    x-network:
      use_cloudmap: False
    environment:
      spring_profiles_active: DEV
secrets:
  BY_API_CREDS:
    x-secrets:
      Name: BY_API_Clientid_Secret_Dev
      JsonKeys:
        - Key: BY_App_Client_Id_Dev
          Name: BY_App_Client_Id_Dev        
        - Key: BY_Secret_Dev
          Name: BY_Secret_Dev
        - Key: BY_Grant_Type_Dev
          Name: BY_Grant_Type_Dev
        - Key: BY_Scope_Dev
          Name: BY_Scope_Dev 

[Container] 2021/03/02 16:14:54 Running command ecs-compose-x create -n ${DEPLOYMENT_NAME:-dis-by-http-client} --format yaml -f docker-compose.yml -f envs/dev.yml \
-b ${CFN_TPL_BUCKET} -d outputs/dev/
2021-03-02 16:14:54 [INFO], Adding secret BY_API_CREDS to settings
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.3/bin/ecs-compose-x", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ecs_composex/cli.py", line 171, in main
    settings = ComposeXSettings(**vars(args))
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ecs_composex/common/settings.py", line 427, in __init__
    self.set_content(kwargs, content)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ecs_composex/common/settings.py", line 628, in set_content
    self.set_secrets()
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ecs_composex/common/settings.py", line 448, in set_secrets
    secret = ComposeSecret(secret_name, secret_def, self)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ecs_composex/secrets/compose_secrets.py", line 188, in __init__
    self.add_json_keys()
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/ecs_composex/secrets/compose_secrets.py", line 206, in add_json_keys
    raise KeyError(
KeyError: ('For Secrets JSON Key support, you must specify', ['SecretKey'], 'Got', dict_keys(['Key', 'Name']))
[Container] 2021/03/02 16:14:54 Command did not exit successfully ecs-compose-x create -n ${DEPLOYMENT_NAME:-dis-by-http-client} --format yaml -f docker-compose.yml -f envs/dev.yml \
-b ${CFN_TPL_BUCKET} -d outputs/dev/
 exit status 1
[Container] 2021/03/02 16:14:54 Phase complete: BUILD State: FAILED
[Container] 2021/03/02 16:14:54 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ecs-compose-x create -n ${DEPLOYMENT_NAME:-dis-by-http-client} --format yaml -f docker-compose.yml -f envs/dev.yml \
-b ${CFN_TPL_BUCKET} -d outputs/dev/
. Reason: exit status 1
 

**Expected behavior**
A success message like this " Adding secret BY_API_CREDS to settings"

**Logs**
If applicable, add logs of errors using from ECS ComposeX

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora/Windows/Mac]
 - Python version (3.6,3.7,3.8)
 - If you were doing things from a branch, which one?
 - Commit ID ?
 - Tag/Version?

**Comment by JohnPreston** [comment]
Hi @pramodvkrishna 
Sorry if the docs did not call that out.
The syntax for secrets expects a list of dict

```
JsonKeys:
  - SecretKey: <the key in JSON>
```

If you want to change the name of the variable exposed with the value of the secret, then
```
JsonKeys:
  - SecretKey: SOMETHING_ELSE
    VarName: SomethingElse
```

Alternatively, there are some transforms available as well.

**Comment by JohnPreston** [comment]
One observation @pramodvkrishna 

Your resources are set

```yaml
reservations:
  cpus: "0.5"
  memory: 1G
```
but your JVM has -Xms512M and -Xmx1G

I'd recommend update to 
```yaml
reservations:
  cpus: "0.5"
  memory: 512M
limits:
  cpus: "0.5"
  memory: 1G
```
That way you are aligning your Xms and Xms to the service deploy.resources :)

**Comment by pramodvkrishna** [comment]
Thanks @JohnPreston for the update. The issue can be closed now.
