### ISSUE TITLE
Status output as the AWS build is happening

### ISSUE THREAD

**Issue by sterichards** [compose-x/ecs_composex#424]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
A status output whilst the AWS build is happening to give live output of which AWS resource creation is happening

**Describe alternatives you've considered**
Logging into CloudFormation and watching the status there but CF is an ugly interface and the process of logging into AWS is becoming more tedious and slow by the day (Captcha :( )

**Additional context**

**Comment by JohnPreston** [comment]
Implemented a `plan` that generates a recursive CloudFormation ChangeSet and shows the high level changes about to happen, and whether or not you want to apply it.
As for the update as it is deploying, this will require either a specific lib to do that neatly to use or some ncurses specifically just to refresh in a friendly way.

**Comment by JohnPreston** [comment]
The display as it happens is a little more painful than I would have hoped.
Will release the `plan` command option which allows to create the recursive ChangeSets in CloudFormation.
