### ISSUE TITLE
Duplicate Export Names when using multiple DynamoDb tables

### ISSUE THREAD

**Issue by krishin-js** [compose-x/ecs_composex#444]
Requirement: Multiple DynamoDB tables are to be created and one of the services will need access to those tables.

Error received looking at the resulting CFN template: 

Template format error: The Outputs section contains duplicate Export names: [my-services-dev::Arn, my-services-dev::TableName]. Specify a unique name for each export.

Buildspec reference: ecs_composex>=0.13.2

**Comment by JohnPreston** [comment]
Hi @krishin-js 
Do you have the source yaml definition you used for `x-dynamodb` ?
Thank you,
