### ISSUE TITLE
Indicate successful ECR scan result in logs

### ISSUE THREAD

**Issue by krishin-js** [compose-x/ecs_composex#485]
**Is your feature request related to a problem? Please describe.**
Given the scan is performed
When there is no error
Then there is no indication of the scan result.

**Describe the solution you'd like**
Given the scan is performed
When there is no error
Then we should be presented with the scan result
And a comparison of the scan result with the Threshold values.

**Comment by JohnPreston** [comment]
Fixed by 42b442f9030aa3f292e4ccc3403d820023114256
Will be in 0.15.9 and above.
Thanks for the request :pray:
