### ISSUE TITLE
InvalidLocationConstraint when running init

### ISSUE THREAD

**Issue by richstokes** [compose-x/ecs_composex#495]
**Describe the bug**
```
ecs-compose-x init

2021-08-17 11:12:39 [ERROR], Error whilst creating the bucket
2021-08-17 11:12:39 [ERROR], An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
```

**Expected behavior**
Should create the bucket

**Desktop (please complete the following information):**
 - OS: Latest Macos
 - Python version 3.8.9
 - ECS ComposeX 0.15.9

**Comment by JohnPreston** [comment]
Thanks @richstokes 
I will have a look at that! If you have existing bucket you can get the files in there in the meantime.

**Comment by richstokes** [comment]
Roger that. FWIW I think this error may be due to us using the us-east-1 region (`AWS_REGION` is set to this in my local env vars), and if you set that as the param when creating a bucket, you get this error.

**Comment by JohnPreston** [comment]
@richstokes 
Can I check what region your session was set to?

**Comment by richstokes** [comment]
I have both these vars set;

```
AWS_DEFAULT_REGION=us-east-1
AWS_REGION=us-east-1
```

**Comment by JohnPreston** [comment]
I guess that is ine to add to the test suite. Test most things in eu west 1 and eu central .
Will make sure to add 2 us regions for giod measure

**Comment by richstokes** [comment]
Or you want something like "if region=us-east-1, then dont send the location param when creating the bucket"

**Comment by JohnPreston** [comment]
@richstokes 
If you could confirm that #496  fixes that issue for you too, I can merge this and it will make it to 0.16.0 
Thank you,

**Comment by richstokes** [comment]
hmm, it doesn't let me checkout that branch 🤔 

```
git checkout "fix/init-new-bucket"
error: pathspec 'fix/init-new-bucket' did not match any file(s) known to git
```

**Comment by richstokes** [comment]
Oh I see, the instructions point to a different repo ❓ 
https://docs.compose-x.io/installation.html

**Comment by richstokes** [comment]
Is there an easy way to build/run it? I ran `python setup.py install` but not sure where its gone:

```
Copying UNKNOWN-0.0.0-py3.8.egg to /Users/rich/.asdf/installs/python/3.8.9/lib/python3.8/site-packages
UNKNOWN 0.0.0 is already the active version in easy-install.pth
```

Not really familiar with how python installs packages

**Comment by JohnPreston** [comment]
Opened a new PR to fix the install notes (_ring bell of shame_) https://github.com/compose-x/ecs_composex/pull/497
Thanks for reporting this too.

Try

```bash
pip install -e .
```
or
```
pip install poetry
poetry install
```

**Comment by richstokes** [comment]
`pip install -e .` gives me:

```
ERROR: Command errored out with exit status 1: /Users/rich/.asdf/installs/python/3.8.9/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'./compose-x/ecs_composex/setup.py'"'"'; __file__='"'"'./compose-x/ecs_composex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by JohnPreston** [comment]
Okay, this is one for me to ask the [poetry](https://github.com/python-poetry/poetry) community about and I will do a special doc for mac users. I assume you are on MacOS given the path of your user directory?

**Comment by JohnPreston** [comment]
testing on a mac I put my hands on I get 
```
  Running setup.py develop for ecs-composex
    ERROR: Command errored out with exit status 1:
     command: /Users/john.mille/venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/john.mille/composex-test/setup.py'"'"'; __file__='"'"'/Users/john.mille/composex-test/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/john.mille/composex-test/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
```
You are getting the same thing I presume ?

**Comment by JohnPreston** [comment]
got it to work on macos with the following
```bash
git clone https://github.com/compose-x/ecs_composex.git
python3 -m venv testing
source venv/bin/activate
cd ecs_composex
pip install pip -U
pip install setuptools
pip install  .
```

**Comment by JohnPreston** [comment]
If you feel like abandoning the python ship, from your current branch run

```bash
docker build -f cli.Dockerfile -t compose-x:test .
```

Then you can run compose-x from docker
```bash
docker run --rm -v ~/.aws:/root/.aws compose-x:test init
```
and subsequent commands 
```bash
docker run --rm -v ~/.aws:/root/.aws compose-x:test -h
```

**Comment by richstokes** [comment]
Yeah I'm lost / dont have the time to wrestle with python dev environments :-)

If you get the fix pushed and I can install/upgrade with a 1-line pip command I'd be happy to try again.

**Comment by JohnPreston** [comment]
More than understandable @richstokes 
Let me come back to you on this.
