### ISSUE TITLE
Cannot deploy service to existing ECS Cluster

### ISSUE THREAD

**Issue by eric-anderton-at-sony** [compose-x/ecs_composex#499]
**Describe the bug**
When creating a new stack using existing  ECS cluster, CloudFormation cannot create EcsServiceDefinition.

```
Resource handler returned message: "Invalid request provided: CreateService error: The platform version must be null when specifying an EC2 launch type. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException;
```

**To Reproduce**
1. Install: `pip install 'ecs-composex[ecrscan]'`
2. Execute: `ecs-compose-x up -f docker-stack.yml -n $PROJECT_NAME -d . --role-arn "$ROLE_ARN"`
3. docker-stack.yml:
```
---
version: "3.7"

x-cluster:
  Lookup: MY_CLUSTER_NAME

x-vpc:
  Use:
    VpcId: MY_VPC_ID
    PublicSubnets:
     - PUBLIC_SUBNET_FOR_VPC
    AppSubnets:
      - APP_SUBNET_FOR_VPC
    StorageSubnets:
      - STORAGE_SUBNET_FOR_VPC

services:
  session-cache:
    image: redis:6.0.5-alpine
```

**Expected behavior**
The generated CloudFormation template deploys the stack specified in the compose file.

I also see that the design defaults to FARGATE which is preferred, but I'm left wondering how CloudFormation thinks this is an EC2 type deployment.  For that matter, I'm not sure how I would override that from ecs-compose-x on an existing cluster - the options for cluster Use/Lookup and Properties, appear to be mutually exclusive.

**Logs**
Log is below with some redactions. Overall, the CLI was happy with the compose file I used and ran without error.  The error in this report is only visible within AWS in the CloudFormation Stacks panel for the sessioncache.config.json template; and you have to be quick to catch it before it rolls back.

```
ecs-compose-x up -f docker-stack.yml -n $PROJECT_NAME -d . --role-arn "$ROLE_ARN" 
2021-08-19 20:16:36 [INFO], Mapped session-cache-data to session-cache
2021-08-19 20:16:37 [WARNING], No x-dns defined and no mesh nor service registry defined. Skipping
2021-08-19 20:16:37 [INFO], Found ECS Cluster MY_CLUSTER_NAME. Setting EcsClusterName accordingly.
2021-08-19 20:16:37 [WARNING], session-cache does not have RAM settings.Based on CPU, it will pick the smaller RAM Fargate supports
2021-08-19 20:16:37 [WARNING], session-cache does not have RAM settings.Based on CPU, it will pick the smaller RAM Fargate supports
2021-08-19 20:16:37 [WARNING], No ports were defined for the services in sessioncache. Not creating a service in CloudMap
2021-08-19 20:16:37 [INFO], No external rules defined. Skipping.
2021-08-19 20:16:37 [ERROR], No scaling range was defined for the service and rule HighCpuUsageAndMaxScaledOut requires it. Skipping
2021-08-19 20:16:37 [ERROR], No scaling range was defined for the service and rule HighRamUsageAndMaxScaledOut requires it. Skipping
2021-08-19 20:16:37 [INFO], sessioncache.json uploaded successfully to https://MY_S3_BUCKET_AND_PATH/sessioncache.json
2021-08-19 20:16:37 [INFO], sessioncache.params.json uploaded successfully to https:///MY_S3_BUCKET_AND_PATH/sessioncache.params.json
2021-08-19 20:16:37 [INFO], sessioncache.config.json uploaded successfully to https:///MY_S3_BUCKET_AND_PATH/sessioncache.config.json
2021-08-19 20:16:37 [INFO], MY_PROJECT_NAME.json uploaded successfully to https:///MY_S3_BUCKET_AND_PATH/andert-dev-polarity.json
2021-08-19 20:16:38 [INFO], Stack MY_PROJECT_NAME successfully deployed.

```
**Desktop (please complete the following information):**
 - OS: Ubuntu Bionic
 - Python 3.9.6
 - Installed latest ecs_composex from pypi  (ECS ComposeX 0.16.0)

**Comment by JohnPreston** [comment]
Hi @eric-anderton-at-sony 
Let me have a look into this.

**Comment by JohnPreston** [comment]
Hi @eric-anderton-at-sony 
You have not done anything wrong at all and thanks so much for reporting this.
You are correct, `Use` and `Lookup` are mutually exclusive.
Where I believe the problem is right now is that you specified an ECS Cluster which I am guessing uses EC2 instances, and when making the API call to ECS, CFN is trying to create the service with a FargatePlatform Version, which is not compatible with EC2 based deployment. 

I am not entirely sure why CFN just tried to create the service in EC2 mode where in the CFN template it clearly says to use Fargate, my guess is that you might not have a FARGATE capacity provider configured in your cluster if your cluster was created a while back, before clusters all came with a default FARGATE configuration, and so ECS falls back to EC2 mode but then has this parameter that breaks it.

So if you could verify this for me that'd be amazing.

So what I am doing now is, if you specify `x-cluster.Lookup` I will verify that there is or not a capacity provider for Fargate, and if none, will instruct that the mode to use for all services should be `EC2` and not `FARGATE`.

I am also adding an additional service.deploy.labels called `ecs.compute.platform` that will allow a user to override the compute platform to allow for EC2/FARGATE/EXTERNAL (now that EC2 anywhere is GA).

**Comment by JohnPreston** [comment]
With the fixes in #500 

Created services on Fargate first and then changed the configuration to run on EC2
![image](https://user-images.githubusercontent.com/1236150/130212642-66931d0e-7be3-4015-b68f-2ed6e866ecbd.png)
ECS Services got replaced successfully and services deployed on EC2
```bash
docker ps 
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS                    PORTS               NAMES
89acd59f0b58        373709687836.dkr.ecr.eu-west-1.amazonaws.com/frontend   "nginx -g 'daemon of…"   3 minutes ago       Up 3 minutes                                  ecs-frontend-3-frontend-e487d38bca958c991a00
90d2350535bb        amazon/amazon-ecs-pause:0.1.0                           "/pause"                 3 minutes ago       Up 3 minutes                                  ecs-frontend-3-internalecspause-d896c29485aaec3e0000
35e6faad71ca        redis:6.0.5-alpine                                      "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes                                  ecs-sessioncache-3-session-cache-d4928492b6dba7861c00
e03c94e85874        amazon/amazon-ecs-pause:0.1.0                           "/pause"                 3 minutes ago       Up 3 minutes                                  ecs-sessioncache-3-internalecspause-b0cbdce5f58fb99b9b01
70cbac6238e2        amazon/amazon-ecs-agent:latest                          "/agent"                 13 minutes ago      Up 13 minutes (healthy)                       ecs-agent

```

![image](https://user-images.githubusercontent.com/1236150/130213179-1ef3635c-522a-42cb-8b8a-09696a455a90.png)

**Comment by eric-anderton-at-sony** [comment]
@JohnPreston Thank you for the stellar support.  I've been racking my brain on this for a while now.  An override for the compute platform should do the trick! 

It turns out I do not have a default provider set.  My lack of experience here is showing: I'm not sure what the default capacityProvider setting is as far as AWS is concerned, but I 'm guessing that it's "EC2".  I think this backs up your analysis:

```json
$ aws ecs describe-clusters --clusters tf-ecs-cluster
{
    "clusters": [
        {
            "clusterArn": "ECS_CLUSTER_ARN",
            "clusterName": "ECS_CLUSTER_NAME",
            "status": "ACTIVE",
            "registeredContainerInstancesCount": 0,
            "runningTasksCount": 4,
            "pendingTasksCount": 0,
            "activeServicesCount": 2,
            "statistics": [],
            "tags": [],
            "settings": [
                {
                    "name": "containerInsights",
                    "value": "disabled"
                }
            ],
            "capacityProviders": [],
            "defaultCapacityProviderStrategy": []
        }
    ],
    "failures": []
}
```

**Comment by JohnPreston** [comment]
Sure thing @eric-anderton-at-sony 
The trick is, if you create the cluster with 
```bash
aws ecs create-cluster --cluster-name testing
{
    "cluster": {
        "clusterArn": "arn:aws:ecs:eu-west-1:2111111111111:cluster/testing",
        "clusterName": "testing",
        "status": "ACTIVE",
        "registeredContainerInstancesCount": 0,
        "runningTasksCount": 0,
        "pendingTasksCount": 0,
        "activeServicesCount": 0,
        "statistics": [],
        "tags": [],
        "settings": [
            {
                "name": "containerInsights",
                "value": "enabled"
            }
        ],
        "capacityProviders": [],
        "defaultCapacityProviderStrategy": []
    }
}
```
No capacity provider is set at all, not even the fargate ones.
However when created in the AWS Console,
```json
[
  {
    "clusterArn": "arn:aws:ecs:eu-west-1:211111111111:cluster/testinginconsole",
    "clusterName": "testinginconsole",
    "status": "ACTIVE",
    "registeredContainerInstancesCount": 0,
    "runningTasksCount": 0,
    "pendingTasksCount": 0,
    "activeServicesCount": 0,
    "statistics": [],
    "tags": [],
    "settings": [
      {
        "name": "containerInsights",
        "value": "enabled"
      }
    ],
    "capacityProviders": [
      "FARGATE_SPOT",
      "FARGATE"
    ],
    "defaultCapacityProviderStrategy": []
  }
]

```
Some capacity provider is set by default. Which is something that I hate, the console tries to make life easy I guess.
So I was incorrect, clusters created via API do not have the FARGATE providers by default.

Yes in absence of any capacity provider it seems to presume that you run in EC2 mode.

For you to try now, if you can to confirm that fixed the behaviour, run 

```bash
git clone https://github.com/compose-x/ecs_composex
python -m venv venv
source venv/bin/activate
cd ecs_composex
git checkout feature/deploy.ecs.compute.platform
make install # easiest way if you have make

```
and in your docker-compose file just add
```yaml
services:
  session-cache:
    image: redis:6.0.5-alpine
    deploy:
      labels:
        ecs.compute.platform: EC2
```
OR

change nothing, and compose-x **should** (it worked for me so hopefully you too) detect that there is no fargate and automatically set that up.

**Comment by JohnPreston** [comment]
@eric-anderton-at-sony  if you want to add FARGATE as capacity provider
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-capacity-providers.html#fargate-capacity-providers-existing-cluster

**Comment by JohnPreston** [comment]
@eric-anderton-at-sony 

I updated the [docs](https://github.com/compose-x/ecs_composex/blob/617c71a57b67c8c012ac870f560e786502cdcea3/docs/syntax/compose_x/ecs.details/deploy.rst) with the extracts of above messages to help out. If / when you have had a chance to test this branch locally give me a :+1:  or :-1: so I can merge this in.

**Comment by eric-anderton-at-sony** [comment]
@JohnPreston - You're g2g on this merge.  I was able to test on your branch and get my stack past the error cited.  I'm in the doldrums on something else - but I'm confident that's on me.  Thanks again for the great support.

**Comment by JohnPreston** [comment]
@eric-anderton-at-sony Amazing.
Feel free to join [Slack](https://join.slack.com/t/compose-x/shared_invite/zt-uihmlsiq-sVyYHOQBnSBFctS5~PUHzw) to ping me in your journey in addition to creating issues here :+1: 
Thanks a lot @eric-anderton-at-sony
