### ISSUE TITLE
[BUG] x-sns - JSON Schema not found for validation

### ISSUE THREAD

**Issue by gliptak** [compose-x/ecs_composex#689]
**Describe the bug**

```
[ WARNING] x-sns - JSON Schema not found for validation. Render may contain errors
```

**To Reproduce**
1. How you installed ECS ComposeX'...' Docker
2. How you are executing it ? : As a CLI tool, as a library, in lambda? CLI
3. Link / share your Docker compose file https://github.com/compose-x/wordpress-demo

```
[ WARNING] x-sns - JSON Schema not found for validation. Render may contain errors
```

**Expected behavior**

I would like to have x-sns section validated

#74 
**Logs**
If applicable, add logs of errors using from ECS ComposeX

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora/Windows/Mac]
 - Python version (3.6,3.7,3.8)
 - If you were doing things from a branch, which one?
 - Commit ID ?
 - Tag/Version? ECS ComposeX 0.23.24

**Comment by JohnPreston** [comment]
Thanks for reporting this @gliptak 
I will have a look into it :)
