### ISSUE TITLE
[FR] ELBv2 Network LB without using Elastic IP Addresses

### ISSUE THREAD

**Issue by thorfi** [compose-x/ecs_composex#724]
### Feature Request

Allow creating a ELBv2 internet-facing network Load Balancer without using Elastic IP Addresses.

#### Details

Need an option to remove the allocation of Elastic IP Addresses to an Internet Facing Network ELB.

Alternatively default to not using EIPs and make the EIPs an opt in setting.

#### Additional context

Network Load Balancer does not need EIP, e.g.:
<img width="860" alt="Screenshot 2023-12-04 at 13 27 26" src="https://github.com/compose-x/ecs_composex/assets/185992/25081e5f-4538-4fd1-9fd9-9fee1989d990">

**Comment by JohnPreston** [comment]
Hey @thorfi
It used to be a requirement to use EIPs when setting a NLB publicly(at least, that's how I took it). Never noticed that requirement went away.
Will add a flag to disable that behaviour.

**Comment by thorfi** [comment]
Thanks!
