### ISSUE TITLE
elbv2 validation HealthCheckTimeoutSeconds and HealthCheckIntervalSeconds might be incorrect?

### ISSUE THREAD

**Issue by louismollick** [compose-x/ecs_composex#732]
https://github.com/compose-x/ecs_composex/blob/9c3be5bf32fa5a095ff0071e11e344c90949f44b/ecs_composex/elbv2/elbv2_ecs.py#L328C16-L328C16

Here in `handle_ping_settings`: 
```
        ("HealthCheckIntervalSeconds", (2, 120)),
        ("HealthCheckTimeoutSeconds", (2, 10)),
```

But based on the docs I would have expected:
```
        ("HealthCheckIntervalSeconds", (5, 300)),
        ("HealthCheckTimeoutSeconds", (2, 120)),
```

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html

Hence with the following `healthcheck`:
`healthcheck: 5001:HTTP:2:10:300:30:/:200`

I'm getting during `ecs-compose-x up`:
```
2023-12-30 17:17:29 [   ERROR] Value for HealthCheckIntervalSeconds is not valid. Must be in range of (2, 120)
2023-12-30 17:17:29 [   ERROR] Value for HealthCheckTimeoutSeconds is not valid. Must be in range of (2, 10)
```

Though not really urgent, since it still deploys to AWS fine & AWS does their own validations.

**Comment by JohnPreston** [comment]
Hello @louismollick 
Thanks for spotting this. The LB module is going to get some love soon to try to handle this kind of things better.
Alternatively if you are getting the wrong settings, you can set the full on TGT Attributes one by one.

Would you  like to open a PR to fix this?
