### ISSUE TITLE
[Question] Is compose-x/wordpress-demo still a working example?

### ISSUE THREAD

**Issue by aanno** [compose-x/ecs_composex#738]
I tried ecs_composex on the [wordpress-demo](https://github.com/compose-x/wordpress-demo). However, I run into an error and reported it [there](https://github.com/compose-x/wordpress-demo/issues/1).

I wonder if I should expect to wordpress lab/demo to run out of the box?!?

**Comment by JohnPreston** [comment]
Thanks for this @aanno 
I haven't updated this in a while, but that shouldn't be too long.

**Comment by JohnPreston** [comment]
@aanno if you wouldn't mind giving it a try from the https://github.com/compose-x/wordpress-demo/pull/2 and let me know how this goes for you?

**Comment by aanno** [comment]
Thank you very much for your support!

I will comment directly in https://github.com/compose-x/wordpress-demo/pull/2
