### ISSUE TITLE
[DOCS] nginx example missing Dockerfile

### ISSUE THREAD

**Issue by mrmattwilkins** [compose-x/ecs_composex#765]
In docker-compose.yaml in the nginx example you reference a Dockerfile, but don't say what should go in it.  Perhaps something like

```
FROM nginx:1.25
COPY app /usr/share/nginx/html
```

?

**Comment by JohnPreston** [comment]
There is a Dockerfile with

```
ARG BASE_IMAGE=nginx:latest

FROM $BASE_IMAGE
COPY app/* /usr/share/nginx/html

```

presuming there is something in `app/*` (which for the demo, there is), that should work.
