### ISSUE TITLE
[DOCS] nginx example missig AWS_REGION

### ISSUE THREAD

**Issue by mrmattwilkins** [compose-x/ecs_composex#766]
you have a 
```
export REGISTRY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-$AWS_DEFAULT_REGION}.amazonaws.com/
```
but nowhere is your default region set.  The aws configure asks you for default region but it doesn't get into environment vars.

**Comment by JohnPreston** [comment]
Should be fixed with d7a56805095c15d9400abf5b10ff7b0b0cd834b5
Thanks for reporting this!
